import type { Restaurant } from "./types";

// Names and coordinates are sourced from OpenStreetMap around Singapore's CBD.
// Queue, match, traffic, reward, and offer fields remain simulated MVP data.
export const restaurants: Restaurant[] = [
  { id: "dumpling-darlings", name: "Dumpling Darlings @ Amoy", emoji: "🥟", image: "linear-gradient(135deg,#ef6a43,#f7b32b)", description: "An Amoy Street stop for dumplings and noodles.", lat: 1.2804865, lng: 103.8469844, distanceKm: 0.61, cravings: ["spicy", "comfort"], dietary: ["vegetarian"], price: 2, queue: "red", waitMinutes: 24, hiddenGem: false, bonusPoints: 0, match: 96 },
  { id: "song-fa", name: "Song Fa Bak Kut Teh", emoji: "🍲", image: "linear-gradient(135deg,#8eaf6b,#f7d878)", description: "Bak kut teh on New Bridge Road near the Singapore River.", lat: 1.2890187, lng: 103.8477137, distanceKm: 0.76, cravings: ["comfort", "healthy"], dietary: [], price: 2, queue: "green", waitMinutes: 4, hiddenGem: false, bonusPoints: 40, match: 89, coupon: { label: "20% off lunch", code: "SONGFA20", expiresAt: "2026-12-31", verified: false } },
  { id: "coconut-club", name: "The Coconut Club", emoji: "🥥", image: "linear-gradient(135deg,#f7b32b,#e1623f)", description: "Singaporean cooking on Beach Road with coconut at its heart.", lat: 1.3006805, lng: 103.8601805, distanceKm: 2.15, cravings: ["spicy", "comfort"], dietary: ["halal"], price: 3, queue: "green", waitMinutes: 6, hiddenGem: false, bonusPoints: 50, match: 91, coupon: { label: "10% off lunch", code: "COCONUT10", expiresAt: "2026-12-31", verified: false } },
  { id: "grain-traders", name: "Grain Traders", emoji: "🥗", image: "linear-gradient(135deg,#5c8a4a,#b8d99c)", description: "Customisable grain bowls on Market Street.", lat: 1.2817841, lng: 103.8500914, distanceKm: 0.25, cravings: ["healthy"], dietary: ["vegan", "vegetarian", "gluten-free"], price: 2, queue: "amber", waitMinutes: 13, hiddenGem: false, bonusPoints: 20, match: 94 },
  { id: "waa-cow", name: "Waa Cow! Marina One", emoji: "🍚", image: "linear-gradient(135deg,#c98552,#f1c27d)", description: "Rice bowls at Marina One in the Downtown Core.", lat: 1.276711, lng: 103.8524818, distanceKm: 0.75, cravings: ["comfort"], dietary: [], price: 2, queue: "amber", waitMinutes: 11, hiddenGem: true, bonusPoints: 30, match: 86, coupon: { label: "$3 off a rice bowl", code: "WAACOW3", expiresAt: "2026-12-31", verified: false } },
  { id: "lau-pa-sat", name: "Lau Pa Sat", emoji: "🍢", image: "linear-gradient(135deg,#d99c59,#7fb069)", description: "A historic CBD food court packed with local stalls.", lat: 1.2806167, lng: 103.8504802, distanceKm: 0.33, cravings: ["spicy", "healthy", "comfort"], dietary: ["vegan", "vegetarian", "halal"], price: 1, queue: "green", waitMinutes: 3, hiddenGem: false, bonusPoints: 60, match: 84 },
  { id: "china-square-food-court", name: "China Square Food Court", emoji: "🍱", image: "linear-gradient(135deg,#f0b35c,#e8784d)", description: "A compact food court near China Square in the CBD.", lat: 1.2828473, lng: 103.8493041, distanceKm: 0.26, cravings: ["comfort", "healthy", "surprise"], dietary: [], price: 1, queue: "green", waitMinutes: 5, hiddenGem: true, bonusPoints: 35, match: 88 },
  { id: "shahi-maharaja", name: "Shahi Maharaja", emoji: "🍛", image: "linear-gradient(135deg,#d85f3f,#f5bd45)", description: "An Indian restaurant near Boat Quay and the Singapore River.", lat: 1.2868595, lng: 103.8494116, distanceKm: 0.46, cravings: ["spicy", "comfort"], dietary: ["vegetarian"], price: 2, queue: "green", waitMinutes: 6, hiddenGem: true, bonusPoints: 45, match: 90 },
  { id: "hong-lim-food-centre", name: "Hong Lim Food Centre", emoji: "🍜", image: "linear-gradient(135deg,#de7047,#f2c35c)", description: "A Chinatown food centre with a broad mix of local stalls.", lat: 1.2852802, lng: 103.8459808, distanceKm: 0.66, cravings: ["spicy", "comfort", "surprise"], dietary: [], price: 1, queue: "amber", waitMinutes: 10, hiddenGem: false, bonusPoints: 25, match: 92 },
  { id: "jumbo-seafood", name: "JUMBO Seafood Riverside", emoji: "🦀", image: "linear-gradient(135deg,#dd614a,#f19c79)", description: "Seafood dining on Upper Circular Road by the river.", lat: 1.2892592, lng: 103.8482726, distanceKm: 0.75, cravings: ["spicy", "comfort", "surprise"], dietary: [], price: 3, queue: "amber", waitMinutes: 12, hiddenGem: false, bonusPoints: 10, match: 87 },
  { id: "no-signboard-seafood", name: "No Signboard Seafood", emoji: "🦐", image: "linear-gradient(135deg,#e78256,#f1c16d)", description: "A Singapore seafood restaurant near Clarke Quay.", lat: 1.289084, lng: 103.8556767, distanceKm: 0.78, cravings: ["spicy", "healthy", "comfort"], dietary: [], price: 3, queue: "green", waitMinutes: 7, hiddenGem: false, bonusPoints: 15, match: 85 },
  { id: "lee-tong-kee", name: "Lee Tong Kee Ipoh Hor Fun", emoji: "🍲", image: "linear-gradient(135deg,#b88555,#e9ca8d)", description: "Hor fun on South Bridge Road in Chinatown.", lat: 1.2815637, lng: 103.8447442, distanceKm: 0.79, cravings: ["comfort", "healthy"], dietary: [], price: 1, queue: "green", waitMinutes: 5, hiddenGem: true, bonusPoints: 40, match: 89 },
  { id: "yum-cha-chinatown", name: "Yum Cha Chinatown", emoji: "🥟", image: "linear-gradient(135deg,#d66a45,#f4c16e)", description: "Chinese dim sum on Trengganu Street in Chinatown.", lat: 1.2829189, lng: 103.8439174, distanceKm: 0.86, cravings: ["comfort", "surprise"], dietary: [], price: 2, queue: "amber", waitMinutes: 9, hiddenGem: false, bonusPoints: 20, match: 90 },
  { id: "liao-fan", name: "Liao Fan Hawker Chan", emoji: "🍗", image: "linear-gradient(135deg,#c96a43,#edb36a)", description: "Soy sauce chicken rice and noodles at Chinatown Complex.", lat: 1.2819879, lng: 103.8432653, distanceKm: 0.94, cravings: ["comfort"], dietary: [], price: 1, queue: "amber", waitMinutes: 14, hiddenGem: false, bonusPoints: 25, match: 93 },
  { id: "casa-vostra", name: "Casa Vostra", emoji: "🍕", image: "linear-gradient(135deg,#c95c43,#f1c770)", description: "Italian dining at Raffles City on North Bridge Road.", lat: 1.2932247, lng: 103.8532339, distanceKm: 1.11, cravings: ["comfort", "surprise"], dietary: ["vegetarian"], price: 2, queue: "green", waitMinutes: 6, hiddenGem: false, bonusPoints: 20, match: 88 },
  { id: "hongdae-korean-bbq", name: "Hongdae Korean BBQ", emoji: "🥩", image: "linear-gradient(135deg,#b84d3c,#ef9d55)", description: "Korean barbecue on Neil Road near Tanjong Pagar.", lat: 1.2790473, lng: 103.841753, distanceKm: 1.2, cravings: ["spicy", "comfort"], dietary: [], price: 2, queue: "green", waitMinutes: 7, hiddenGem: true, bonusPoints: 35, match: 91 },
  { id: "tanjong-pagar-food-centre", name: "Tanjong Pagar Food Centre", emoji: "🍽️", image: "linear-gradient(135deg,#e38a4d,#f4cc74)", description: "A neighbourhood food centre serving a range of Asian dishes.", lat: 1.2765516, lng: 103.8430933, distanceKm: 1.21, cravings: ["spicy", "healthy", "comfort", "surprise"], dietary: [], price: 1, queue: "green", waitMinutes: 6, hiddenGem: false, bonusPoints: 45, match: 86 },
  { id: "shinji-kanesaka", name: "Shinji by Kanesaka", emoji: "🍣", image: "linear-gradient(135deg,#76a78c,#d8d9a6)", description: "A sushi restaurant inside Raffles Hotel on Seah Street.", lat: 1.2947239, lng: 103.854586, distanceKm: 1.3, cravings: ["healthy", "surprise"], dietary: ["gluten-free"], price: 3, queue: "green", waitMinutes: 4, hiddenGem: false, bonusPoints: 15, match: 90 },
  { id: "shunjuu-izakaya", name: "Shunjuu Izakaya", emoji: "🍢", image: "linear-gradient(135deg,#6f9b7c,#d7bd75)", description: "A Japanese izakaya near Robertson Quay.", lat: 1.2910861, lng: 103.8409947, distanceKm: 1.46, cravings: ["healthy", "comfort", "surprise"], dietary: [], price: 2, queue: "amber", waitMinutes: 9, hiddenGem: true, bonusPoints: 30, match: 87 },
  { id: "su-shi-piao-xiang", name: "Su Shi Piao Xiang Vegetarian", emoji: "🥬", image: "linear-gradient(135deg,#69a35d,#c8db87)", description: "A vegetarian and vegan Chinese eatery inside Fortune Centre.", lat: 1.3000559, lng: 103.8524194, distanceKm: 1.85, cravings: ["healthy", "comfort"], dietary: ["vegan", "vegetarian"], price: 1, queue: "green", waitMinutes: 5, hiddenGem: true, bonusPoints: 50, match: 92 },
];
