import type { Restaurant } from "./types";

// MOCK MVP DATA: seeded around Singapore's CBD. Replace through a RestaurantSource
// adapter when a Places provider is selected; the UI only consumes Restaurant[].
export const restaurants: Restaurant[] = [
  { id: "dumpling-darlings", name: "Dumpling Darlings @ Amoy", emoji: "🥟", image: "linear-gradient(135deg,#ef6a43,#f7b32b)", description: "An Amoy Street stop for dumplings and noodles.", lat: 1.2804865, lng: 103.8469844, distanceKm: 0.61, cravings: ["spicy", "comfort"], dietary: ["vegetarian"], price: 2, queue: "red", waitMinutes: 24, hiddenGem: false, bonusPoints: 0, match: 96 },
  { id: "song-fa", name: "Song Fa Bak Kut Teh", emoji: "🍲", image: "linear-gradient(135deg,#8eaf6b,#f7d878)", description: "Bak kut teh on New Bridge Road near the Singapore River.", lat: 1.2890187, lng: 103.8477137, distanceKm: 0.76, cravings: ["comfort", "healthy"], dietary: [], price: 2, queue: "green", waitMinutes: 4, hiddenGem: false, bonusPoints: 40, match: 89, coupon: { label: "20% off lunch", code: "SONGFA20", expiresAt: "2026-12-31", verified: false } },
  { id: "coconut-club", name: "The Coconut Club", emoji: "🥥", image: "linear-gradient(135deg,#f7b32b,#e1623f)", description: "Singaporean cooking on Beach Road with coconut at its heart.", lat: 1.3006805, lng: 103.8601805, distanceKm: 2.15, cravings: ["spicy", "comfort"], dietary: ["halal"], price: 3, queue: "green", waitMinutes: 6, hiddenGem: false, bonusPoints: 50, match: 91, coupon: { label: "10% off lunch", code: "COCONUT10", expiresAt: "2026-12-31", verified: false } },
  { id: "grain-traders", name: "Grain Traders", emoji: "🥗", image: "linear-gradient(135deg,#5c8a4a,#b8d99c)", description: "Customisable grain bowls on Market Street.", lat: 1.2817841, lng: 103.8500914, distanceKm: 0.25, cravings: ["healthy"], dietary: ["vegan", "vegetarian", "gluten-free"], price: 2, queue: "amber", waitMinutes: 13, hiddenGem: false, bonusPoints: 20, match: 94 },
  { id: "waa-cow", name: "Waa Cow! Marina One", emoji: "🍚", image: "linear-gradient(135deg,#c98552,#f1c27d)", description: "Rice bowls at Marina One in the Downtown Core.", lat: 1.276711, lng: 103.8524818, distanceKm: 0.75, cravings: ["comfort"], dietary: [], price: 2, queue: "amber", waitMinutes: 11, hiddenGem: true, bonusPoints: 30, match: 86, coupon: { label: "$3 off a rice bowl", code: "WAACOW3", expiresAt: "2026-12-31", verified: false } },
  { id: "lau-pa-sat", name: "Lau Pa Sat", emoji: "🍢", image: "linear-gradient(135deg,#d99c59,#7fb069)", description: "A historic CBD food court packed with local stalls.", lat: 1.2806167, lng: 103.8504802, distanceKm: 0.33, cravings: ["spicy", "healthy", "comfort"], dietary: ["vegan", "vegetarian", "halal"], price: 1, queue: "green", waitMinutes: 3, hiddenGem: false, bonusPoints: 60, match: 84 },
];
